/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EditArea: typeof import('./src/components/EditArea.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LoginComponent: typeof import('./src/components/account/LoginComponent.vue')['default']
    PostItem: typeof import('./src/components/postItem/PostItem.vue')['default']
    PostItemCommentItem: typeof import('./src/components/postItem/PostItemCommentItem.vue')['default']
    PostItemComments: typeof import('./src/components/postItem/PostItemComments.vue')['default']
    PostItemFooter: typeof import('./src/components/postItem/PostItemFooter.vue')['default']
    PostItemHeader: typeof import('./src/components/postItem/PostItemHeader.vue')['default']
    PostItemImages: typeof import('./src/components/postItem/PostItemImages.vue')['default']
    RegisterComponent: typeof import('./src/components/account/RegisterComponent.vue')['default']
    RequireLoginDialog: typeof import('./src/components/dialogs/RequireLoginDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleAvatar: typeof import('./src/components/SimpleAvatar.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
